import * as piece from './piece-names';

const board = {
    a8: piece.BLACK_ROOK_1,
    b8: piece.BLACK_KNIGHT_1,
    c8: piece.BLACK_BISHOP_1,
    d8: piece.BLACK_QUEEN_1,
    e8: piece.BLACK_KING,
    f8: piece.BLACK_BISHOP_2,
    g8: piece.BLACK_KNIGHT_2,
    h8: piece.BLACK_ROOK_2,

    a7: piece.BLACK_PAWN_1,
    b7: piece.BLACK_PAWN_2,
    c7: piece.BLACK_PAWN_3,
    d7: piece.BLACK_PAWN_4,
    e7: piece.BLACK_PAWN_5,
    f7: piece.BLACK_PAWN_6,
    g7: piece.BLACK_PAWN_7,
    h7: piece.BLACK_PAWN_8,

    a6: '',
    b6: '',
    c6: '',
    d6: '',
    e6: '',
    f6: '',
    g6: '',
    h6: '',

    a5: '',
    b5: '',
    c5: '',
    d5: '',
    e5: '',
    f5: '',
    g5: '',
    h5: '',

    a4: '',
    b4: '',
    c4: '',
    d4: '',
    e4: '',
    f4: '',
    g4: '',
    h4: '',

    a3: '',
    b3: '',
    c3: '',
    d3: '',
    e3: '',
    f3: '',
    g3: '',
    h3: '',

    a2: piece.WHITE_PAWN_1,
    b2: piece.WHITE_PAWN_2,
    c2: piece.WHITE_PAWN_3,
    d2: piece.WHITE_PAWN_4,
    e2: piece.WHITE_PAWN_5,
    f2: piece.WHITE_PAWN_6,
    g2: piece.WHITE_PAWN_7,
    h2: piece.WHITE_PAWN_8,

    a1: piece.WHITE_ROOK_1,
    b1: piece.WHITE_KNIGHT_1,
    c1: piece.WHITE_BISHOP_1,
    d1: piece.WHITE_QUEEN_1,
    e1: piece.WHITE_KING,
    f1: piece.WHITE_BISHOP_2,
    g1: piece.WHITE_KNIGHT_2,
    h1: piece.WHITE_ROOK_2,
};

export default board;
